dofile_once( "__MOD_ACTION_UTILS__comp_utils.lua" )

local entity_id = GetUpdatedEntityID()
first_comp( entity_id, "ProjectileComponent", function( comp )
	ComponentSetValue2( comp, "collide_with_world", false )
	ComponentSetValue2( comp, "collide_with_entities", false )
end )
first_comp( entity_id, "VelocityComponent", function( comp )
	ComponentSetValue2( comp, "liquid_drag", 0 )
	ComponentSetValue2( comp, "displace_liquid", false )
end )
for_comps( entity_id, "GameAreaEffectComponent", function( comp )
	EntitySetComponentIsEnabled( entity_id, comp, false )
end )